ALTER TABLE comms.transcripts
ADD COLUMN IF NOT EXISTS is_require_followup BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS followup_method VARCHAR(50),
ADD COLUMN IF NOT EXISTS followup_request_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS followup_complete_date TIMESTAMP;
